const products = [
  {
    id: "1",
    name: "Men Moccs",
    category: "Moccs",
    category: "men",
    oldPrice: "8999.00",
    newPrice: "7199.00",
    discount: "20%",
    colors: ["BROWN"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product1/1.webp", "./Pictures/Product1/2.webp", "./Pictures/Product1/3.webp", "./Pictures/Product1/4.webp"]
  },
  {
    id: "2",
    name: "Men Moccs",
    category: "Moccs",
    category: "men",
    oldPrice: "6399.00",
    newPrice: "7999.00",
    discount: "20%",
    colors: ["BLACK"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product2/1.webp", "./Pictures/Product2/2.webp", "./Pictures/Product2/3.webp", "./Pictures/Product2/4.webp"]
  },
  {
    id: "3",
    name: "Men Moccs",
    category: "Moccs",
    category: "men",
    oldPrice: "8999.00",
    newPrice: "7199.00",
    discount: "20%",
    colors: ["BLACK"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product3/1.webp", "./Pictures/Product3/2.webp", "./Pictures/Product3/3.webp", "./Pictures/Product3/4.webp"]
  },
  {
    id: "4",
    name: "Men Moccs",
    category: "Moccs",
    category: "men",
    oldPrice: "6399.00",
    newPrice: "7999.00",
    discount: "20%",
    colors: ["BROWN"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product4/1.webp", "./Pictures/Product4/2.webp", "./Pictures/Product4/3.webp", "./Pictures/Product4/4.webp"]
  },
  {
    id: "5",
    name: "Men Formal Shoes",
    category: "Formal",
    category: "men",
    oldPrice: "9999.00",
    newPrice: "7999.00",
    discount: "20%",
    colors: ["BROWN"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product5/1.webp", "./Pictures/Product5/2.webp", "./Pictures/Product5/3.webp", "./Pictures/Product5/4.webp"]
  },
  {
    id: "6",
    name: "Men Formal Shoes",
    category: "Formal",
    category: "men",
    oldPrice: "9999.00",
    newPrice: "7999.00",
    discount: "20%",
    colors: ["BLACK"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product6/1.webp", "./Pictures/Product6/2.webp", "./Pictures/Product6/3.webp", "./Pictures/Product6/4.webp"]
  },
  {
    id: "7",
    name: "Men Formal Shoes",
    category: "Formal",
    category: "men",
    oldPrice: "4999.00",
    newPrice: "3999.00",
    discount: "20%",
    colors: ["BLACK"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product7/1.webp", "./Pictures/Product7/2.webp", "./Pictures/Product7/3.webp", "./Pictures/Product7/4.webp"]
  },
  {
    id: "8",
    name: "Men Formal Shoes",
    category: "Formal",
    category: "men",
    oldPrice: "9999.00",
    newPrice: "7999.00",
    discount: "20%",
    colors: ["BROWN"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product8/1.webp", "./Pictures/Product8/2.webp", "./Pictures/Product8/3.webp", "./Pictures/Product8/4.webp"]
  },
  {
    id: "9",
    name: "Men Chappal",
    category: "Chappal",
    category: "men",
    oldPrice: "4699.00",
    newPrice: "3579.00",
    discount: "20%",
    colors: ["BROWN"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product9/1.webp", "./Pictures/Product9/2.webp", "./Pictures/Product9/3.webp", "./Pictures/Product9/4.webp"]
  },
  {
    id: "10",
    name: "Men Chappal",
    category: "Chappal",
    category: "men",
    oldPrice: "4699.00",
    newPrice: "3579.00",
    discount: "20%",
    colors: ["BROWN"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product10/1.webp", "./Pictures/Product10/2.webp", "./Pictures/Product10/3.webp", "./Pictures/Product10/4.webp"]
  },
  {
    id: "11",
    name: "Men Chappal",
    category: "Chappal",
    category: "men",
    oldPrice: "4699.00",
    newPrice: "3579.00",
    discount: "20%",
    colors: ["BROWN"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product11/1.webp", "./Pictures/Product11/2.webp", "./Pictures/Product11/3.webp", "./Pictures/Product11/4.webp"]
  },
  {
    id: "12",
    name: "Men Chappal",
    category: "Chappal",
    category: "men",
    oldPrice: "4699.00",
    newPrice: "3579.00",
    discount: "20%",
    colors: ["BROWN"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product12/1.webp", "./Pictures/Product12/2.webp", "./Pictures/Product12/3.webp", "./Pictures/Product12/4.webp"]
  },
  {
    id: "13",
    name: "Men Joggers",
    category: "Joggers",
    category: "men",
    oldPrice: "4699.00",
    newPrice: "3579.00",
    discount: "20%",
    colors: ["BLACK"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product13/1.webp", "./Pictures/Product13/2.webp", "./Pictures/Product13/3.webp", "./Pictures/Product13/4.webp"]
  },
  {
    id: "14",
    name: "Men Joggers",
    category: "Joggers",
    category: "men",
    oldPrice: "4699.00",
    newPrice: "3579.00",
    discount: "20%",
    colors: ["BLACK"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product14/1.webp", "./Pictures/Product14/2.webp", "./Pictures/Product14/3.webp", "./Pictures/Product14/4.webp"]
  },
  {
    id: "15",
    name: "Men Joggers",
    category: "Joggers",
    category: "men",
    oldPrice: "4699.00",
    newPrice: "3579.00",
    discount: "20%",
    colors: ["WHITE"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product15/1.webp", "./Pictures/Product15/2.webp", "./Pictures/Product15/3.webp", "./Pictures/Product15/4.webp"]
  },
  {
    id: "16",
    name: "Men Joggers",
    category: "Joggers",
    category: "men",
    oldPrice: "4699.00",
    newPrice: "3579.00",
    discount: "20%",
    colors: ["BLACK"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product16/1.webp", "./Pictures/Product16/2.webp", "./Pictures/Product16/3.webp", "./Pictures/Product16/4.webp"]
  },
  {
    id: "1",
    name: "Men Moccs",
    category: "Moccs",
    category: "men",
    oldPrice: "8999.00",
    newPrice: "7199.00",
    discount: "20%",
    colors: ["BROWN"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product1/1.webp", "./Pictures/Product1/2.webp", "./Pictures/Product1/3.webp", "./Pictures/Product1/4.webp"]
  },
  {
    id: "2",
    name: "Men Moccs",
    category: "Moccs",
    category: "men",
    oldPrice: "6399.00",
    newPrice: "7999.00",
    discount: "20%",
    colors: ["BLACK"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product2/1.webp", "./Pictures/Product2/2.webp", "./Pictures/Product2/3.webp", "./Pictures/Product2/4.webp"]
  },
  {
    id: "3",
    name: "Men Moccs",
    category: "Moccs",
    category: "men",
    oldPrice: "8999.00",
    newPrice: "7199.00",
    discount: "20%",
    colors: ["BLACK"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product3/1.webp", "./Pictures/Product3/2.webp", "./Pictures/Product3/3.webp", "./Pictures/Product3/4.webp"]
  },
  {
    id: "4",
    name: "Men Moccs",
    category: "Moccs",
    category: "men",
    oldPrice: "6399.00",
    newPrice: "7999.00",
    discount: "20%",
    colors: ["BROWN"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product4/1.webp", "./Pictures/Product4/2.webp", "./Pictures/Product4/3.webp", "./Pictures/Product4/4.webp"]
  },
  {
    id: "5",
    name: "Men Formal Shoes",
    category: "Formal",
    category: "men",
    oldPrice: "9999.00",
    newPrice: "7999.00",
    discount: "20%",
    colors: ["BROWN"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product5/1.webp", "./Pictures/Product5/2.webp", "./Pictures/Product5/3.webp", "./Pictures/Product5/4.webp"]
  },
  {
    id: "6",
    name: "Men Formal Shoes",
    category: "Formal",
    category: "men",
    oldPrice: "9999.00",
    newPrice: "7999.00",
    discount: "20%",
    colors: ["BLACK"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product6/1.webp", "./Pictures/Product6/2.webp", "./Pictures/Product6/3.webp", "./Pictures/Product6/4.webp"]
  },
  {
    id: "7",
    name: "Men Formal Shoes",
    category: "Formal",
    category: "men",
    oldPrice: "4999.00",
    newPrice: "3999.00",
    discount: "20%",
    colors: ["BLACK"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product7/1.webp", "./Pictures/Product7/2.webp", "./Pictures/Product7/3.webp", "./Pictures/Product7/4.webp"]
  },
  {
    id: "8",
    name: "Men Formal Shoes",
    category: "Formal",
    category: "men",
    oldPrice: "9999.00",
    newPrice: "7999.00",
    discount: "20%",
    colors: ["BROWN"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product8/1.webp", "./Pictures/Product8/2.webp", "./Pictures/Product8/3.webp", "./Pictures/Product8/4.webp"]
  },
  {
    id: "9",
    name: "Men Chappal",
    category: "Chappal",
    category: "men",
    oldPrice: "4699.00",
    newPrice: "3579.00",
    discount: "20%",
    colors: ["BROWN"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product9/1.webp", "./Pictures/Product9/2.webp", "./Pictures/Product9/3.webp", "./Pictures/Product9/4.webp"]
  },
  {
    id: "10",
    name: "Men Chappal",
    category: "Chappal",
    oldPrice: "4699.00",
    newPrice: "3579.00",
    discount: "20%",
    colors: ["BROWN"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product10/1.webp", "./Pictures/Product10/2.webp", "./Pictures/Product10/3.webp", "./Pictures/Product10/4.webp"]
  },
  {
    id: "11",
    name: "Men Chappal",
    category: "Chappal",
    category: "men",
    oldPrice: "4699.00",
    newPrice: "3579.00",
    discount: "20%",
    colors: ["BROWN"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product11/1.webp", "./Pictures/Product11/2.webp", "./Pictures/Product11/3.webp", "./Pictures/Product11/4.webp"]
  },
  {
    id: "12",
    name: "Men Chappal",
    category: "Chappal",
    category: "men",
    oldPrice: "4699.00",
    newPrice: "3579.00",
    discount: "20%",
    colors: ["BROWN"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product12/1.webp", "./Pictures/Product12/2.webp", "./Pictures/Product12/3.webp", "./Pictures/Product12/4.webp"]
  },
  {
    id: "13",
    name: "Men Joggers",
    category: "Joggers",
    category: "men",
    oldPrice: "4699.00",
    newPrice: "3579.00",
    discount: "20%",
    colors: ["BLACK"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product13/1.webp", "./Pictures/Product13/2.webp", "./Pictures/Product13/3.webp", "./Pictures/Product13/4.webp"]
  },
  {
    id: "14",
    name: "Men Joggers",
    category: "Joggers",
    category: "men",
    oldPrice: "4699.00",
    newPrice: "3579.00",
    discount: "20%",
    colors: ["BLACK"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product14/1.webp", "./Pictures/Product14/2.webp", "./Pictures/Product14/3.webp", "./Pictures/Product14/4.webp"]
  },
  {
    id: "15",
    name: "Men Joggers",
    category: "Joggers",
    category: "men",
    oldPrice: "4699.00",
    newPrice: "3579.00",
    discount: "20%",
    colors: ["WHITE"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product15/1.webp", "./Pictures/Product15/2.webp", "./Pictures/Product15/3.webp", "./Pictures/Product15/4.webp"]
  },
  {
    id: "16",
    name: "Men Joggers",
    category: "Joggers",
    category: "men",
    oldPrice: "4699.00",
    newPrice: "3579.00",
    discount: "20%",
    colors: ["BLACK"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product16/1.webp", "./Pictures/Product16/2.webp", "./Pictures/Product16/3.webp", "./Pictures/Product16/4.webp"]
  },
  {
    id: "1",
    name: "Men Moccs",
    category: "Moccs",
    category: "men",
    oldPrice: "8999.00",
    newPrice: "7199.00",
    discount: "20%",
    colors: ["BROWN"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product1/1.webp", "./Pictures/Product1/2.webp", "./Pictures/Product1/3.webp", "./Pictures/Product1/4.webp"]
  },
  {
    id: "2",
    name: "Men Moccs",
    category: "Moccs",
    category: "men",
    oldPrice: "6399.00",
    newPrice: "7999.00",
    discount: "20%",
    colors: ["BLACK"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product2/1.webp", "./Pictures/Product2/2.webp", "./Pictures/Product2/3.webp", "./Pictures/Product2/4.webp"]
  },
  {
    id: "3",
    name: "Men Moccs",
    category: "Moccs",
    category: "men",
    oldPrice: "8999.00",
    newPrice: "7199.00",
    discount: "20%",
    colors: ["BLACK"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product3/1.webp", "./Pictures/Product3/2.webp", "./Pictures/Product3/3.webp", "./Pictures/Product3/4.webp"]
  },
  {
    id: "4",
    name: "Men Moccs",
    category: "Moccs",
    category: "men",
    oldPrice: "6399.00",
    newPrice: "7999.00",
    discount: "20%",
    colors: ["BROWN"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product4/1.webp", "./Pictures/Product4/2.webp", "./Pictures/Product4/3.webp", "./Pictures/Product4/4.webp"]
  },
  {
    id: "5",
    name: "Men Formal Shoes",
    category: "Formal",
    category: "men",
    oldPrice: "9999.00",
    newPrice: "7999.00",
    discount: "20%",
    colors: ["BROWN"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product5/1.webp", "./Pictures/Product5/2.webp", "./Pictures/Product5/3.webp", "./Pictures/Product5/4.webp"]
  },
  {
    id: "6",
    name: "Men Formal Shoes",
    category: "Formal",
    category: "men",
    oldPrice: "9999.00",
    newPrice: "7999.00",
    discount: "20%",
    colors: ["BLACK"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product6/1.webp", "./Pictures/Product6/2.webp", "./Pictures/Product6/3.webp", "./Pictures/Product6/4.webp"]
  },
  {
    id: "7",
    name: "Men Formal Shoes",
    category: "Formal",
    category: "men",
    oldPrice: "4999.00",
    newPrice: "3999.00",
    discount: "20%",
    colors: ["BLACK"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product7/1.webp", "./Pictures/Product7/2.webp", "./Pictures/Product7/3.webp", "./Pictures/Product7/4.webp"]
  },
  {
    id: "8",
    name: "Men Formal Shoes",
    category: "Formal",
    category: "men",
    oldPrice: "9999.00",
    newPrice: "7999.00",
    discount: "20%",
    colors: ["BROWN"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product8/1.webp", "./Pictures/Product8/2.webp", "./Pictures/Product8/3.webp", "./Pictures/Product8/4.webp"]
  },
  {
    id: "9",
    name: "Men Chappal",
    category: "Chappal",
    category: "men",
    oldPrice: "4699.00",
    newPrice: "3579.00",
    discount: "20%",
    colors: ["BROWN"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product9/1.webp", "./Pictures/Product9/2.webp", "./Pictures/Product9/3.webp", "./Pictures/Product9/4.webp"]
  },
  {
    id: "10",
    name: "Men Chappal",
    category: "Chappal",
    category: "men",
    oldPrice: "4699.00",
    newPrice: "3579.00",
    discount: "20%",
    colors: ["BROWN"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product10/1.webp", "./Pictures/Product10/2.webp", "./Pictures/Product10/3.webp", "./Pictures/Product10/4.webp"]
  },
  {
    id: "11",
    name: "Men Chappal",
    category: "Chappal",
    category: "men",
    oldPrice: "4699.00",
    newPrice: "3579.00",
    discount: "20%",
    colors: ["BROWN"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product11/1.webp", "./Pictures/Product11/2.webp", "./Pictures/Product11/3.webp", "./Pictures/Product11/4.webp"]
  },
  {
    id: "12",
    name: "Men Chappal",
    category: "Chappal",
    category: "men",
    oldPrice: "4699.00",
    newPrice: "3579.00",
    discount: "20%",
    colors: ["BROWN"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product12/1.webp", "./Pictures/Product12/2.webp", "./Pictures/Product12/3.webp", "./Pictures/Product12/4.webp"]
  },
  {
    id: "13",
    name: "Men Joggers",
    category: "Joggers",
    category: "men",
    oldPrice: "4699.00",
    newPrice: "3579.00",
    discount: "20%",
    colors: ["BLACK"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product13/1.webp", "./Pictures/Product13/2.webp", "./Pictures/Product13/3.webp", "./Pictures/Product13/4.webp"]
  },
  {
    id: "14",
    name: "Men Joggers",
    category: "Joggers",
    category: "men",
    oldPrice: "4699.00",
    newPrice: "3579.00",
    discount: "20%",
    colors: ["BLACK"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product14/1.webp", "./Pictures/Product14/2.webp", "./Pictures/Product14/3.webp", "./Pictures/Product14/4.webp"]
  },
  {
    id: "15",
    name: "Men Joggers",
    category: "Joggers",
    category: "men",
    oldPrice: "4699.00",
    newPrice: "3579.00",
    discount: "20%",
    colors: ["WHITE"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product15/1.webp", "./Pictures/Product15/2.webp", "./Pictures/Product15/3.webp", "./Pictures/Product15/4.webp"]
  },
  {
    id: "16",
    name: "Men Joggers",
    category: "Joggers",
    category: "men",
    oldPrice: "4699.00",
    newPrice: "3579.00",
    discount: "20%",
    colors: ["BLACK"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product16/1.webp", "./Pictures/Product16/2.webp", "./Pictures/Product16/3.webp", "./Pictures/Product16/4.webp"]
  },
  {
    id: "1",
    name: "Men Moccs",
    category: "Moccs",
    category: "men",
    oldPrice: "8999.00",
    newPrice: "7199.00",
    discount: "20%",
    colors: ["BROWN"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product1/1.webp", "./Pictures/Product1/2.webp", "./Pictures/Product1/3.webp", "./Pictures/Product1/4.webp"]
  },
  {
    id: "2",
    name: "Men Moccs",
    category: "Moccs",
    category: "men",
    oldPrice: "6399.00",
    newPrice: "7999.00",
    discount: "20%",
    colors: ["BLACK"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product2/1.webp", "./Pictures/Product2/2.webp", "./Pictures/Product2/3.webp", "./Pictures/Product2/4.webp"]
  },
  {
    id: "3",
    name: "Men Moccs",
    category: "Moccs",
    category: "men",
    oldPrice: "8999.00",
    newPrice: "7199.00",
    discount: "20%",
    colors: ["BLACK"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product3/1.webp", "./Pictures/Product3/2.webp", "./Pictures/Product3/3.webp", "./Pictures/Product3/4.webp"]
  },
  {
    id: "4",
    name: "Men Moccs",
    category: "Moccs",
    category: "men",
    oldPrice: "6399.00",
    newPrice: "7999.00",
    discount: "20%",
    colors: ["BROWN"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product4/1.webp", "./Pictures/Product4/2.webp", "./Pictures/Product4/3.webp", "./Pictures/Product4/4.webp"]
  },
  {
    id: "5",
    name: "Men Formal Shoes",
    category: "Formal",
    category: "men",
    oldPrice: "9999.00",
    newPrice: "7999.00",
    discount: "20%",
    colors: ["BROWN"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product5/1.webp", "./Pictures/Product5/2.webp", "./Pictures/Product5/3.webp", "./Pictures/Product5/4.webp"]
  },
  {
    id: "6",
    name: "Men Formal Shoes",
    category: "Formal",
    category: "men",
    oldPrice: "9999.00",
    newPrice: "7999.00",
    discount: "20%",
    colors: ["BLACK"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product6/1.webp", "./Pictures/Product6/2.webp", "./Pictures/Product6/3.webp", "./Pictures/Product6/4.webp"]
  },
  {
    id: "7",
    name: "Men Formal Shoes",
    category: "Formal",
    category: "men",
    oldPrice: "4999.00",
    newPrice: "3999.00",
    discount: "20%",
    colors: ["BLACK"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product7/1.webp", "./Pictures/Product7/2.webp", "./Pictures/Product7/3.webp", "./Pictures/Product7/4.webp"]
  },
  {
    id: "8",
    name: "Men Formal Shoes",
    category: "Formal",
    category: "men",
    oldPrice: "9999.00",
    newPrice: "7999.00",
    discount: "20%",
    colors: ["BROWN"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product8/1.webp", "./Pictures/Product8/2.webp", "./Pictures/Product8/3.webp", "./Pictures/Product8/4.webp"]
  },
  {
    id: "9",
    name: "Men Chappal",
    category: "Chappal",
    category: "men",
    oldPrice: "4699.00",
    newPrice: "3579.00",
    discount: "20%",
    colors: ["BROWN"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product9/1.webp", "./Pictures/Product9/2.webp", "./Pictures/Product9/3.webp", "./Pictures/Product9/4.webp"]
  },
  {
    id: "10",
    name: "Men Chappal",
    category: "Chappal",
    category: "men",
    oldPrice: "4699.00",
    newPrice: "3579.00",
    discount: "20%",
    colors: ["BROWN"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product10/1.webp", "./Pictures/Product10/2.webp", "./Pictures/Product10/3.webp", "./Pictures/Product10/4.webp"]
  },
  {
    id: "11",
    name: "Men Chappal",
    category: "Chappal",
    category: "men",
    oldPrice: "4699.00",
    newPrice: "3579.00",
    discount: "20%",
    colors: ["BROWN"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product11/1.webp", "./Pictures/Product11/2.webp", "./Pictures/Product11/3.webp", "./Pictures/Product11/4.webp"]
  },
  {
    id: "12",
    name: "Men Chappal",
    category: "Chappal",
    category: "men",
    oldPrice: "4699.00",
    newPrice: "3579.00",
    discount: "20%",
    colors: ["BROWN"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product12/1.webp", "./Pictures/Product12/2.webp", "./Pictures/Product12/3.webp", "./Pictures/Product12/4.webp"]
  },
  {
    id: "13",
    name: "Men Joggers",
    category: "Joggers",
    category: "men",
    oldPrice: "4699.00",
    newPrice: "3579.00",
    discount: "20%",
    colors: ["BLACK"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product13/1.webp", "./Pictures/Product13/2.webp", "./Pictures/Product13/3.webp", "./Pictures/Product13/4.webp"]
  },
  {
    id: "14",
    name: "Men Joggers",
    category: "Joggers",
    category: "men",
    oldPrice: "4699.00",
    newPrice: "3579.00",
    discount: "20%",
    colors: ["BLACK"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product14/1.webp", "./Pictures/Product14/2.webp", "./Pictures/Product14/3.webp", "./Pictures/Product14/4.webp"]
  },
  {
    id: "15",
    name: "Men Joggers",
    category: "Joggers",
    category: "men",
    oldPrice: "4699.00",
    newPrice: "3579.00",
    discount: "20%",
    colors: ["WHITE"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product15/1.webp", "./Pictures/Product15/2.webp", "./Pictures/Product15/3.webp", "./Pictures/Product15/4.webp"]
  },
  {
    id: "16",
    name: "Men Joggers",
    category: "Joggers",
    category: "men",
    oldPrice: "4699.00",
    newPrice: "3579.00",
    discount: "20%",
    colors: ["BLACK"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product16/1.webp", "./Pictures/Product16/2.webp", "./Pictures/Product16/3.webp", "./Pictures/Product16/4.webp"]
  },
  {
    id: "17",
    name: "Women Slipper",
    category: "Slipper",
    category: "women",
    oldPrice: "3199.00",
    newPrice: "2559.00",
    discount: "20%",
    colors: ["GOLDEN"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product17/1.webp", "./Pictures/Product17/2.webp", "./Pictures/Product17/3.webp", "./Pictures/Product17/4.webp"]
  },
  {
    id: "18",
    name: "Women Slipper",
    category: "Slipper",
    category: "women",
    oldPrice: "3199.00",
    newPrice: "2559.00",
    discount: "20%",
    colors: ["GOLDEN"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product18/1.webp", "./Pictures/Product18/2.webp", "./Pictures/Product18/3.webp", "./Pictures/Product18/4.webp"]
  },
  {
    id: "19",
    name: "Women Sandal",
    category: "Sandal",
    category: "women",
    oldPrice: "3199.00",
    newPrice: "2559.00",
    discount: "20%",
    colors: ["GREY"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product19/1.webp", "./Pictures/Product19/2.webp", "./Pictures/Product19/3.webp", "./Pictures/Product19/4.webp"]
  },
  {
    id: "20",
    name: "Women Sandal",
    category: "Sandal",
    category: "women",
    oldPrice: "3199.00",
    newPrice: "2559.00",
    discount: "20%",
    colors: ["GREY"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product20/1.webp", "./Pictures/Product20/2.webp", "./Pictures/Product20/3.webp", "./Pictures/Product20/4.webp"]
  },
  {
    id: "21",
    name: "Women Slipper",
    category: "Slipper",
    category: "women",
    oldPrice: "3199.00",
    newPrice: "2559.00",
    discount: "20%",
    colors: ["BLACK"],
    sizes: [38, 39, 40, 41, 42],
    images: ["./Pictures/Product21/1.webp", "./Pictures/Product21/2.webp", "./Pictures/Product21/3.webp", "./Pictures/Product21/4.webp"]
  },
  {
    id: "22",
    name: "Girls Slipper",
    category: "kid-slipper",
    category: "kids",
    oldPrice: "1699.00",
    newPrice: "1359.00",
    discount: "20%",
    colors: ["GOLDEN"],
    sizes: [25, 26, 27, 28, 29],
    images: ["./Pictures/Product22/1.webp", "./Pictures/Product22/2.webp", "./Pictures/Product22/3.webp", "./Pictures/Product22/4.webp"]
  },
  {
    id: "23",
    name: "Girls Slipper",
    category: "kid-slipper",
    category: "kids",
    oldPrice: "1699.00",
    newPrice: "1359.00",
    discount: "20%",
    colors: ["FUCHSIA"],
    sizes: [25, 26, 27, 28, 29],
    images: ["./Pictures/Product23/1.webp", "./Pictures/Product23/2.webp", "./Pictures/Product23/3.webp", "./Pictures/Product23/4.webp"]
  },
  {
    id: "24",
    name: "Girls Slipper",
    category: "kid-slipper",
    category: "kids",
    oldPrice: "1699.00",
    newPrice: "1359.00",
    discount: "20%",
    colors: ["WHITE"],
    sizes: [25, 26, 27, 28, 29],
    images: ["./Pictures/Product24/1.webp", "./Pictures/Product24/2.webp", "./Pictures/Product24/3.webp", "./Pictures/Product24/4.webp"]
  },
  {
    id: "25",
    name: "Girls Slipper",
    category: "kid-slipper",
    category: "kids",
    oldPrice: "1699.00",
    newPrice: "1359.00",
    discount: "20%",
    colors: ["PINK"],
    sizes: [25, 26, 27, 28, 29],
    images: ["./Pictures/Product25/1.webp", "./Pictures/Product25/2.webp", "./Pictures/Product25/3.webp", "./Pictures/Product25/4.webp"]
  },
  {
    id: "26",
    name: "Girls Slipper",
    category: "kid-slipper",
    category: "kids",
    oldPrice: "1299.00",
    newPrice: "959.00",
    discount: "20%",
    colors: ["PINK"],
    sizes: [25, 26, 27, 28, 29],
    images: ["./Pictures/Product26/1.webp", "./Pictures/Product26/2.webp", "./Pictures/Product26/3.webp", "./Pictures/Product26/4.webp"]
  },
]